import { entries, pipe, sortBy, unique, flatMap, filter, map } from 'remeda';
import type { ReadonlyDeep } from 'type-fest';
import type { PluginConfig } from '../shared/types.js';
import { NixGenerator } from './generator-base.js';

const gen = new NixGenerator();

const baseUpperNames = [
  'webhook',
  'owner',
  'administrator',
  'moderatorStaff',
  'moderator',
  'voiceModerator',
  'chatModerator',
  'skipHostUpdate',
  'dangerousEnableDevtoolsOnlyEnableIfYouKnowWhatYoureDoing',
  'minWidth',
  'minHeight',
  'isMaximized',
  'isMinimized',
  'windowBounds',
  'openOnStartup',
  'minimizeToTray',
] as const;

const baseLowerPluginTitles: readonly string[] = [];

type PluginCollections = ReadonlyArray<ReadonlyDeep<Record<string, PluginConfig>>>;

function collectLowerPluginTitles(...collections: PluginCollections): string[] {
  const entriesList = flatMap(collections, (collection) => entries(collection));
  const lowerNames = pipe(
    entriesList,
    filter(([, config]) => {
      const name = config.name?.trim();
      if (!name) return false;
      const firstChar = name.slice(0, 1);
      return firstChar.toLowerCase() === firstChar;
    }),
    map(([slug]) => slug)
  );
  return pipe(
    [...baseLowerPluginTitles, ...lowerNames],
    unique(),
    sortBy((name) => name)
  );
}

export function generateParseRulesModule(
  shared: ReadonlyDeep<Record<string, PluginConfig>>,
  vencordOnly: ReadonlyDeep<Record<string, PluginConfig>>,
  equicordOnly: ReadonlyDeep<Record<string, PluginConfig>>
): string {
  const lowerPluginTitles = collectLowerPluginTitles(shared, vencordOnly, equicordOnly);

  const output = gen.attrSet({
    upperNames: [...baseUpperNames],
    lowerPluginTitles,
  });

  return [
    '# This file is auto-generated by scripts/generate-plugin-options',
    '# DO NOT EDIT this file directly; instead update the generator',
    '',
    output,
  ].join('\n');
}
