import { entries, pipe, sortBy, unique, flatMap, filter, map } from 'remeda';
import type { PluginConfig } from '../shared/types.js';
import { NixGenerator, type NixAttrSet } from './generator-base.js';

const gen = new NixGenerator();

const baseUpperNames = [
  'webhook',
  'owner',
  'administrator',
  'moderatorStaff',
  'moderator',
  'voiceModerator',
  'chatModerator',
  'skipHostUpdate',
  'dangerousEnableDevtoolsOnlyEnableIfYouKnowWhatYoureDoing',
  'minWidth',
  'minHeight',
  'isMaximized',
  'isMinimized',
  'windowBounds',
  'openOnStartup',
  'minimizeToTray',
] as const;

const baseLowerPluginTitles: readonly string[] = [];

const baseFakeEnums = {
  zero: [
    'randomCharacters',
    'never',
    'playing',
    'none',
    'everything',
    'all',
    'recentlyActive',
    'normal',
    'highestRole',
    'mostRecent',
    'disabled',
    'compact',
    'plain',
    'whitelist',
  ],
  one: [
    'consistent',
    'always',
    'streaming',
    'discordUptime',
    'titles',
    'only@Mentions',
    'list',
    'datePosted',
    'better',
    'lowestRole',
    'custom',
    'preferDiscord',
    'enabled',
    'onlyServerCount',
    'cozy',
    'muted',
    'animatedDots',
    'blacklist',
  ],
  two: [
    'timestamp',
    'moreThanOne',
    'listening',
    'currentTime',
    'thumbnails',
    'nothing',
    'gallery',
    'projectX',
    'followNoReplyMention',
    'onlyFriendCount',
    'roomy',
    'avatars',
  ],
  three: ['watching', 'customTime', 'serverDefault', 'both'],
  four: ['competing'],
} as const;

type PluginCollections = ReadonlyArray<Readonly<Record<string, PluginConfig>>>;

function collectLowerPluginTitles(...collections: PluginCollections): string[] {
  const entriesList = flatMap(collections, (collection) => entries(collection));
  const lowerNames = pipe(
    entriesList,
    filter(([, config]) => {
      const name = config.name?.trim();
      if (!name) return false;
      const firstChar = name.slice(0, 1);
      return firstChar.toLowerCase() === firstChar;
    }),
    map(([slug]) => slug)
  );
  return pipe(
    [...baseLowerPluginTitles, ...lowerNames],
    unique(),
    sortBy((name) => name)
  );
}

export function generateParseRulesModule(
  shared: Readonly<Record<string, PluginConfig>>,
  vencordOnly: Readonly<Record<string, PluginConfig>>,
  equicordOnly: Readonly<Record<string, PluginConfig>>
): string {
  const lowerPluginTitles = collectLowerPluginTitles(shared, vencordOnly, equicordOnly);

  const fakeEnums: NixAttrSet = {
    zero: [...baseFakeEnums.zero],
    one: [...baseFakeEnums.one],
    two: [...baseFakeEnums.two],
    three: [...baseFakeEnums.three],
    four: [...baseFakeEnums.four],
  };

  const output = gen.attrSet({
    upperNames: [...baseUpperNames],
    lowerPluginTitles,
    fakeEnums,
  });

  return [
    '# This file is auto-generated by scripts/generate-plugin-options',
    '# DO NOT EDIT this file directly; instead update the generator',
    '',
    output,
  ].join('\n');
}
