# This file is auto-generated by scripts/generate-plugin-options
# DO NOT EDIT this file directly; instead update the generator

{ lib, ... }:
let
  inherit (lib) types mkEnableOption mkOption;
in
{
  allCallTimers = {
    enable = mkEnableOption ''Add call timer to all users in a server voice channel. (Equicord-only)'';
    format = mkOption {
      default = "stopwatch";
      description = ''Compact or human readable format:'';
      type = types.enum [
        "stopwatch"
        "human"
      ];
    };
    showRoleColor = mkOption {
      default = true;
      description = ''Show the user's role color (if this plugin in enabled)'';
      type = types.bool;
    };
    showSeconds = mkOption {
      default = true;
      description = ''Show seconds in the timer'';
      type = types.bool;
    };
    showWithoutHover = mkOption {
      default = true;
      description = ''Always show the timer without needing to hover (restart required)'';
      type = types.bool;
    };
    trackSelf = mkOption {
      default = true;
      description = ''Also track yourself'';
      type = types.bool;
    };
    watchLargeGuilds = mkOption {
      default = false;
      description = ''Track users in large guilds. This may cause lag if you're in a lot of large guilds with active voice users. Tested with up to 2000 active voice users with no issues. (restart required)'';
      type = types.bool;
    };
  };
  altKrispSwitch = {
    enable = mkEnableOption ''Makes the Noise Suppression Popout switch between None and Krisp instead of Krisp and Standard (Equicord-only)'';
  };
  alwaysExpandProfiles = {
    enable = mkEnableOption ''Always expands profile popouts to the full modal (Equicord-only)'';
  };
  amITyping = {
    enable = mkEnableOption ''Shows you if other people can see you typing. (Equicord-only)'';
  };
  anammox = {
    enable = mkEnableOption ''A microbial process that plays an important part in the nitrogen cycle (Equicord-only)'';
    billing = mkOption {
      default = true;
      description = ''Remove billing settings (restart required)'';
      type = types.bool;
    };
    dms = mkOption {
      default = true;
      description = ''Remove shops above DMs list (restart required)'';
      type = types.bool;
    };
    emojiList = mkOption {
      default = true;
      description = ''Remove unavailable categories from the emoji picker (restart required)'';
      type = types.bool;
    };
    gift = mkOption {
      default = true;
      description = ''Remove gift button (restart required)'';
      type = types.bool;
    };
    serverBoost = mkOption {
      default = true;
      description = ''Remove server boost info above channel list (restart required)'';
      type = types.bool;
    };
  };
  animalese = {
    enable = mkEnableOption ''Plays animal crossing animalese for every message sent (they yap a lot) (Equicord-only)'';
    messageLengthLimit = mkOption {
      default = 50;
      description = ''Maximum length of message to process'';
      type = types.int;
    };
    pitch = mkOption {
      default = 1.0;
      description = ''Pitch multiplier'';
      type = types.float;
    };
    processOwnMessages = mkOption {
      default = true;
      description = ''Enable to yap your own messages too'';
      type = types.bool;
    };
    soundQuality = mkOption {
      default = "high";
      description = ''Quality of sound to use'';
      type = types.enum [
        "high"
        "med"
        "low"
        "low"
      ];
    };
    speed = mkOption {
      default = 1.0;
      description = ''Speed of the animalese sound'';
      type = types.float;
    };
    volume = mkOption {
      default = 0.5;
      description = ''Volume of the animalese sound'';
      type = types.float;
    };
  };
  atSomeone = {
    enable = mkEnableOption ''Mention someone randomly (Equicord-only)'';
  };
  audioBookShelfRichPresence = {
    enable = mkEnableOption ''Rich presence for AudioBookShelf media server (Equicord-only)'';
    password = mkOption {
      default = null;
      description = ''AudioBookShelf password'';
      type = types.nullOr types.str;
    };
    serverUrl = mkOption {
      default = null;
      description = ''AudioBookShelf server URL (e.g., https://abs.example.com)'';
      type = types.nullOr types.str;
    };
    username = mkOption {
      default = null;
      description = ''AudioBookShelf username'';
      type = types.nullOr types.str;
    };
  };
  autoZipper = {
    enable = mkEnableOption ''Automatically zips specified file types and folders before uploading to Discord (Equicord-only)'';
    extensions = mkOption {
      default = ".psd,.blend,.exe,.dmg,.app,.apk,.iso";
      description = ''Comma-separated list of file extensions to auto-zip (e.g., .psd,.blend,.exe,.dmg)'';
      type = types.str;
    };
  };
  bannersEverywhere = {
    enable = mkEnableOption ''Displays banners in the member list  (Equicord-only)'';
    animate = mkOption {
      default = false;
      description = ''Animate banners'';
      type = types.bool;
    };
    preferNameplate = mkOption {
      default = false;
      description = ''prefer nameplate over banner'';
      type = types.bool;
    };
  };
  betterActivities = {
    enable = mkEnableOption ''Shows activity icons in the member list and allows showing all activities (Equicord-only)'';
  };
  betterAudioPlayer = {
    enable = mkEnableOption ''Adds a spectrograph and oscilloscope visualizer to audio attachment players (Equicord-only)'';
    forceMoveBelow = mkOption {
      default = true;
      description = ''Force the visualizer below the audio player'';
      type = types.bool;
    };
    oscilloscope = mkOption {
      default = true;
      description = ''Enable oscilloscope visualizer'';
      type = types.bool;
    };
    oscilloscopeColor = mkOption {
      default = "255, 255, 255";
      description = ''Color for oscilloscope'';
      type = types.str;
    };
    oscilloscopeSolidColor = mkOption {
      default = false;
      description = ''Use solid color for oscilloscope'';
      type = types.bool;
    };
    spectrograph = mkOption {
      default = true;
      description = ''Enable spectrograph visualizer'';
      type = types.bool;
    };
    spectrographColor = mkOption {
      default = "33, 150, 243";
      description = ''Color for spectrograph'';
      type = types.str;
    };
    spectrographSolidColor = mkOption {
      default = false;
      description = ''Use solid color for spectrograph'';
      type = types.bool;
    };
  };
  betterBanReasons = {
    enable = mkEnableOption ''Create custom reasons to use in the Discord ban modal, and/or show a text input by default instead of the options. (Equicord-only)'';
    isTextInputDefault = mkOption {
      default = false;
      description = ''Shows a text input instead of a select menu by default. (Equivalent to clicking the "Other" option)'';
      type = types.bool;
    };
    reasons = mkOption {
      default = [ ];
      description = ''Your custom reasons'';
      type = types.listOf types.str;
    };
  };
  betterBlockedUsers = {
    enable = mkEnableOption ''Allows you to search in blocked users list and makes names selectable in settings. (Equicord-only)'';
  };
  betterCommands = {
    enable = mkEnableOption ''Enhances the command system with miscellaneous improvements. (Equicord-only)'';
    allowNewlinesInCommands = mkOption {
      default = true;
      description = ''Allow newlines in command inputs (Shift + Enter)'';
      type = types.bool;
    };
    autoFillArguments = mkOption {
      default = true;
      description = ''Automatically fill command with all arguements instead of just required ones'';
      type = types.bool;
    };
  };
  betterInvites = {
    enable = mkEnableOption ''See invites expiration date, view inviter profile and preview discoverable servers before joining by clicking their name (Equicord-only)'';
  };
  betterPlusReacts = {
    enable = mkEnableOption ''The amount of plus before :emoji: is the message to add it to (Equicord-only)'';
  };
  betterQuickReact = {
    enable = mkEnableOption ''Improves the quick react buttons in the message context menu. (Equicord-only)'';
    columns = mkOption {
      default = 4.0;
      description = ''Columns of quick reactions to display'';
      type = types.float;
    };
    compactMode = mkOption {
      default = false;
      description = ''Scales the buttons to 75% of their original scale, whilst increasing the inner emoji to 125% scale. Emojis will be 93.75% of the original size. Recommended to have a minimum of 5 columns'';
      type = types.bool;
    };
    frequentEmojis = mkOption {
      default = true;
      description = ''Use frequently used emojis instead of favourite emojis (restart required)'';
      type = types.bool;
    };
    rows = mkOption {
      default = 2.0;
      description = ''Rows of quick reactions to display'';
      type = types.float;
    };
    scroll = mkOption {
      default = true;
      description = ''Enable scrolling the list of emojis'';
      type = types.bool;
    };
  };
  betterUserArea = {
    enable = mkEnableOption ''Customize and make the user area more clean. (Equicord-only)'';
    alwaysShowUsername = mkOption {
      default = true;
      description = ''Always show username instead of status. (restart required)'';
      type = types.bool;
    };
    removeAudioMenus = mkOption {
      default = true;
      description = ''Remove menus next to mute and deafen buttons. (restart required)'';
      type = types.bool;
    };
    removeAvatarDecoration = mkOption {
      default = true;
      description = ''Remove avatar decoration. (restart required)'';
      type = types.bool;
    };
    removeButtonTooltips = mkOption {
      default = false;
      description = ''Remove button tooltips. (restart required)'';
      type = types.bool;
    };
    removeNameplate = mkOption {
      default = true;
      description = ''Remove nameplate styling. (restart required)'';
      type = types.bool;
    };
    removeUsernameStyles = mkOption {
      default = true;
      description = ''Remove username colors and effects. (restart required)'';
      type = types.bool;
    };
  };
  blockKeywords = {
    enable = mkEnableOption ''Blocks messages containing specific user-defined keywords, as if the user sending them was blocked. (Equicord-only)'';
    blockedWords = mkOption {
      default = "";
      description = ''Comma-seperated list of words to block (restart required)'';
      type = types.str;
    };
    caseSensitive = mkOption {
      default = false;
      description = ''Whether to use a case sensitive search or not (restart required)'';
      type = types.bool;
    };
    ignoreBlockedMessages = mkOption {
      default = true;
      description = ''Completely ignores (recent) new messages bar (restart required)'';
      type = types.bool;
    };
    useRegex = mkOption {
      default = false;
      description = ''Use each value as a regular expression when checking message content (advanced) (restart required)'';
      type = types.bool;
    };
  };
  blockKrisp = {
    enable = mkEnableOption ''Prevent Krisp from loading (Equicord-only)'';
  };
  bypassPinPrompt = {
    enable = mkEnableOption ''Bypass the pin prompt when using the pin functions (Equicord-only)'';
  };
  bypassStatus = {
    enable = mkEnableOption ''Still get notifications from specific sources when in do not disturb mode. Right-click on users/channels/guilds to set them to bypass do not disturb mode. (Equicord-only)'';
    allowOutsideOfDms = mkOption {
      default = false;
      description = ''Allow selected users to bypass status outside of DMs too (acts like a channel/guild bypass, but it's for all messages sent by the selected users)'';
      type = types.bool;
    };
    channels = mkOption {
      default = "";
      description = ''Channels to let bypass (notified when pinged in that channel)'';
      example = "Separate with commas";
      type = types.str;
    };
    guilds = mkOption {
      default = "";
      description = ''Guilds to let bypass (notified when pinged anywhere in guild)'';
      example = "Separate with commas";
      type = types.str;
    };
    notificationSound = mkOption {
      default = true;
      description = ''Whether the notification sound should be played'';
      type = types.bool;
    };
    statusToUse = mkOption {
      default = "dnd";
      description = ''Status to use for whitelist'';
      type = types.enum [
        "online"
        "idle"
        "dnd"
        "invisible"
      ];
    };
    users = mkOption {
      default = "";
      description = ''Users to let bypass (notified for all messages sent in DMs)'';
      example = "Separate with commas";
      type = types.str;
    };
  };
  channelBadges = {
    enable = mkEnableOption ''Adds badges to channels based on their type (Equicord-only)'';
  };
  channelTabs = {
    enable = mkEnableOption ''Group your commonly visited channels in tabs, like a browser (Equicord-only)'';
  };
  characterCounter = {
    enable = mkEnableOption ''Adds a character counter to the chat input (Equicord-only)'';
    colorEffects = mkOption {
      default = true;
      description = ''Turn on or off color effects for getting close to the character limit'';
      type = types.bool;
    };
  };
  cleanChannelName = {
    enable = mkEnableOption ''remove all emoji and decor shit from channel names (Equicord-only)'';
  };
  clientSideBlock = {
    enable = mkEnableOption ''Allows you to locally hide almost all content from any user (Equicord-only)'';
    blockedReplyDisplay = mkOption {
      default = "displayText";
      description = ''What should display instead of the message when someone replies to someone you have hidden (restart required)'';
      type = types.enum [
        "displayText"
        "hideReply"
      ];
    };
    guildBlackList = mkOption {
      default = "";
      description = ''Guild ids to disable functionality in (restart required)'';
      type = types.str;
    };
    guildWhiteList = mkOption {
      default = "";
      description = ''Guild ids to enable functionality in (restart required)'';
      type = types.str;
    };
    hideBlockedMessages = mkOption {
      default = true;
      description = ''Should messages from blocked users should be hidden fully (same as the old noblockedmessages plugin) (restart required)'';
      type = types.bool;
    };
    hideBlockedUsers = mkOption {
      default = true;
      description = ''Should blocked users should also be hidden everywhere (restart required)'';
      type = types.bool;
    };
    hideEmptyRoles = mkOption {
      default = true;
      description = ''Should role headers be hidden if all of their members are blocked (restart required)'';
      type = types.bool;
    };
    hideVc = mkOption {
      default = false;
      description = ''Hide voice channels containing blocked users. (restart required)'';
      type = types.bool;
    };
    usersToBlock = mkOption {
      default = "";
      description = ''User IDs seperated by a comma and a space (restart required)'';
      type = types.str;
    };
  };
  clipsEnhancements = {
    enable = mkEnableOption ''Add more Clip FPS and duration options, plus RPC tagging! (Equicord-only)'';
    clipsLink = mkOption {
      default = { };
      type = types.attrs;
    };
    richPresenceTagging = mkOption {
      default = "whenMatched";
      description = ''When should clips be tagged with the current Rich Presence?'';
      type = types.enum [
        "always"
        "whenMatched"
        "never"
      ];
    };
  };
  commandPalette = {
    enable = mkEnableOption ''Quickly run actions through a searchable command palette (Equicord-only)'';
    customCommands = mkOption {
      default = { };
      description = ''Manage custom command palette entries'';
      type = types.attrs;
    };
    enableTagFilter = mkOption {
      default = true;
      description = ''Show the tag filter bar'';
      type = types.bool;
    };
    hotkey = mkOption {
      default = { };
      description = ''Hotkey used to open the command palette'';
      type = types.attrs;
    };
    showTags = mkOption {
      default = true;
      description = ''Display tag chips for commands'';
      type = types.bool;
    };
    visualStyle = mkOption {
      default = "classic";
      description = ''Palette appearance'';
      type = types.enum [
        "classic"
        "polished"
      ];
    };
  };
  contentWarning = {
    enable = mkEnableOption ''Allows you to specify certain trigger words that will be blurred by default. Hovering/Clicking on the blurred content will reveal it. (Equicord-only)'';
    flagged = mkOption {
      default = { };
      type = types.attrs;
    };
    onClick = mkOption {
      default = false;
      description = ''Only show trigger content on click instead of hover'';
      type = types.bool;
    };
  };
  copyProfileColors = {
    enable = mkEnableOption ''A plugin to copy people's profile gradient colors to clipboard. (Equicord-only)'';
  };
  copyStatusUrls = {
    enable = mkEnableOption ''Copy the users status url when you right-click it (Equicord-only)'';
  };
  copyUserMention = {
    enable = mkEnableOption ''Adds a button to copy user's mention on the user context menu, works best with ValidUser. (Equicord-only)'';
  };
  customFolderIcons = {
    enable = mkEnableOption ''Customize folder icons with any png (Equicord-only)'';
  };
  customSounds = {
    enable = mkEnableOption ''Customize Discord's sounds. (Equicord-only)'';
    overrides = mkOption {
      default = { };
      type = types.attrs;
    };
  };
  customTimestamps = {
    enable = mkEnableOption ''Custom timestamps on messages and tooltips (Equicord-only)'';
    formats = mkOption {
      default = { };
      description = ''Customize the timestamp formats'';
      type = types.attrs;
    };
  };
  customUserColors = {
    enable = mkEnableOption ''Lets you add a custom color to any user, anywhere! Highly recommend to use with typingTweaks and roleColorEverywhere (Equicord-only)'';
    colorInServers = mkOption {
      default = true;
      description = ''If name colors should be changed within servers'';
      type = types.bool;
    };
    dmList = mkOption {
      default = true;
      description = ''Users with custom colors defined will have their name in the dm list colored'';
      type = types.bool;
    };
  };
  decodeBase64 = {
    enable = mkEnableOption ''Decode base64 content of any message and copy the decoded content. (Equicord-only)'';
    clickMethod = mkOption {
      default = "Left";
      description = ''Change the button to decode base64 content of any message.'';
      type = types.enum [
        "Left"
        "Right"
      ];
    };
  };
  disableCameras = {
    enable = mkEnableOption ''Disables cameras in a call by default (Equicord-only)'';
  };
  discordDevBanner = {
    enable = mkEnableOption ''Enables the Discord developer banner, in which displays the build-ID (Equicord-only)'';
  };
  equicordHelper = {
    enable = mkEnableOption ''Used to provide support, fix discord caused crashes, and other misc features. (Equicord-only)'';
    disableDmContextMenu = mkOption {
      default = false;
      description = ''Disables the DM list context menu in favor of the x button (restart required)'';
      type = types.bool;
    };
    noMirroredCamera = mkOption {
      default = false;
      description = ''Prevents the camera from being mirrored on your screen'';
      type = types.bool;
    };
    removeActivitySection = mkOption {
      default = false;
      description = ''Removes the activity section above member list'';
      type = types.bool;
    };
  };
  equicordToolbox = {
    enable = mkEnableOption ''Adds a button next to the inbox button in the channel header that houses Equicord quick actions (Equicord-only)'';
    showPluginMenu = mkOption {
      default = true;
      description = ''Show the plugins menu in the toolbox'';
      type = types.bool;
    };
  };
  equissant = {
    enable = mkEnableOption ''Crossant every specified amount of clicks :trolley: (Equicord-only)'';
    amount = mkOption {
      default = 10;
      description = ''amount of clicks to trigger crossant'';
      type = types.int;
    };
  };
  exitSounds = {
    enable = mkEnableOption ''Play soundboard sounds when you disconnect from voice. (Equicord-only)'';
    soundGuildId = mkOption {
      default = { };
      description = ''Select the server containing the sound.'';
      type = types.attrs;
    };
    soundId = mkOption {
      default = { };
      description = ''Enter the ID of the sound you want to play.'';
      type = types.attrs;
    };
  };
  exportMessages = {
    enable = mkEnableOption ''Allows you to export any message to a file (Equicord-only)'';
    exportContacts = mkOption {
      default = false;
      description = ''Export a list of friends to your clipboard. Adds a new button to the menu bar for the friends tab.'';
      type = types.bool;
    };
    openFileAfterExport = mkOption {
      default = true;
      description = ''Open the exported file in the default file handler after export'';
      type = types.bool;
    };
  };
  fastDeleteChannels = {
    enable = mkEnableOption ''Adds a trash icon to delete channels (Equicord-only)'';
    keyBind = mkOption {
      default = "KeyZ";
      description = ''The key to toggle trash when pressed.'';
      type = types.str;
    };
    reqAlt = mkOption {
      default = false;
      description = ''Require alt to be held.'';
      type = types.bool;
    };
    reqCtrl = mkOption {
      default = true;
      description = ''Require control to be held.'';
      type = types.bool;
    };
    reqShift = mkOption {
      default = true;
      description = ''Require shift to be held.'';
      type = types.bool;
    };
  };
  findReply = {
    enable = mkEnableOption ''Jumps to the earliest reply to a message in a channel (lets you follow past conversations more easily). (Equicord-only)'';
    hideButtonIfNoReply = mkOption {
      default = true;
      description = ''Hides the button if there are no replies to the message (restart required)'';
      type = types.bool;
    };
    includeAuthor = mkOption {
      default = false;
      description = ''Will also search for messages that reply to the author in general, not just that exact message'';
      type = types.bool;
    };
    includePings = mkOption {
      default = false;
      description = ''Will also search for messages that @ the author directly'';
      type = types.bool;
    };
  };
  fixFileExtensions = {
    enable = mkEnableOption ''Fixes file extensions by renaming them to a compatible supported format if possible (Equicord-only)'';
  };
  followVoiceUser = {
    enable = mkEnableOption ''Follow a friend in voice chat. (Equicord-only)'';
    leaveWhenUserLeaves = mkOption {
      default = false;
      description = ''Leave the voice channel when the user leaves. (That can cause you to sometimes enter infinite leave/join loop)'';
      type = types.bool;
    };
    onlyWhenInVoice = mkOption {
      default = true;
      description = ''Only follow the user when you are in a voice channel'';
      type = types.bool;
    };
  };
  fontLoader = {
    enable = mkEnableOption ''Loads any font from Google Fonts (Equicord-only)'';
    applyOnCodeBlocks = mkOption {
      default = false;
      description = ''Apply the font to code blocks'';
      type = types.bool;
    };
    fontSearch = mkOption {
      default = { };
      description = ''Search and select Google Fonts'';
      type = types.attrs;
    };
  };
  forwardAnywhere = {
    enable = mkEnableOption ''If a forward fails send it as a normal message also allows nsfw forwards (Equicord-only)'';
    forwardPreface = mkOption {
      default = ">";
      description = ''What should forwarded from be prefaced with'';
      type = types.enum [
        ">"
        "-#"
      ];
    };
  };
  frequentQuickSwitcher = {
    enable = mkEnableOption ''Rewrites and filters the quick switcher results to be your most frequent channels (Equicord-only)'';
  };
  friendCloud = {
    enable = mkEnableOption ''Adds a /friendcloud command to visualize the users you most interact with (Equicord-only)'';
  };
  friendCodes = {
    enable = mkEnableOption ''Generate FriendCodes to easily add friends (Equicord-only)'';
  };
  friendTags = {
    enable = mkEnableOption ''Allows you to filter by custom tags in the quick switcher by starting a search with & (Equicord-only)'';
    tagConfiguration = mkOption {
      default = { };
      description = ''The tag configuration component'';
      type = types.attrs;
    };
  };
  friendshipRanks = {
    enable = mkEnableOption ''Adds badges showcasing how long you have been friends with a user for (Equicord-only)'';
  };
  fullVcpfp = {
    enable = mkEnableOption ''Makes avatars take up the entire vc tile (Equicord-only)'';
  };
  gensokyoRadioRpc = {
    enable = mkEnableOption ''Discord rich presence for Gensokyo Radio! (Equicord-only)'';
    refreshInterval = mkOption {
      default = 15.0;
      description = ''The interval between activity refreshes (seconds) (restart required)'';
      type = types.float;
    };
  };
  ghosted = {
    enable = mkEnableOption ''A cute ghost will appear if you don't answer their DMs (Equicord-only)'';
    exemptedChannels = mkOption {
      default = "";
      description = ''Comma-separated list of channel IDs to exempt from ghosting (right-click a DM channel to copy its ID)'';
      type = types.str;
    };
    ignoreBots = mkOption {
      default = true;
      description = ''Ignore DMs from bots'';
      type = types.bool;
    };
    scary = mkOption {
      default = false;
      description = ''Something might happen if you ignore someone for too long...'';
      type = types.bool;
    };
    showDmIcons = mkOption {
      default = true;
      description = ''Show ghost icons next to individual DMs'';
      type = types.bool;
    };
    showIndicator = mkOption {
      default = true;
      description = ''Show the ghost counter at the top of the server list'';
      type = types.bool;
    };
  };
  gifCollections = {
    enable = mkEnableOption ''Allows you to create collections of gifs (Equicord-only)'';
    collectionPrefix = mkOption {
      default = "gc:";
      description = ''The prefix for collections (restart required)'';
      type = types.str;
    };
    collectionsSort = mkOption {
      default = { };
      description = ''Decide how to sort collections'';
      type = types.attrs;
    };
    defaultEmptyCollectionImage = mkOption {
      default = "https://c.tenor.com/YEG33HsLEaIAAAAC/parksandrec-oops.gif";
      description = ''The image / gif that will be shown when a collection has no images / gifs'';
      type = types.str;
    };
    exportGifs = mkOption {
      default = { };
      description = ''Export Collections'';
      type = types.attrs;
    };
    importGifs = mkOption {
      default = { };
      description = ''Import Collections'';
      type = types.attrs;
    };
    itemPrefix = mkOption {
      default = "gc-item:";
      description = ''The prefix for gif items (restart required)'';
      type = types.str;
    };
    onlyShowCollections = mkOption {
      default = false;
      description = ''Only show collections (restart required)'';
      type = types.bool;
    };
    preventDuplicates = mkOption {
      default = false;
      description = ''Prevent adding the same GIF to a collection multiple times'';
      type = types.bool;
    };
    resetCollections = mkOption {
      default = { };
      description = ''Reset Collections'';
      type = types.attrs;
    };
    showCopyImageLink = mkOption {
      default = false;
      description = ''Show 'Copy Image Link' option in context menus'';
      type = types.bool;
    };
    stopWarnings = mkOption {
      default = false;
      description = ''Stop deletion warnings'';
      type = types.bool;
    };
  };
  gifRoulette = {
    enable = mkEnableOption ''Adds a command to send a random gif from your favourites, and a one in ten chance to ping the owner of the server (Equicord-only)'';
    pingOwnerChance = mkOption {
      default = true;
      description = ''If there should be a 1 in 10 change to ping the owner of the guild (oh no)'';
      type = types.bool;
    };
  };
  gitHubRepos = {
    enable = mkEnableOption ''Displays a user's public GitHub repositories in their profile (Equicord-only)'';
    showInMiniProfile = mkOption {
      default = true;
      description = ''Show full ui in the mini profile instead of just a button'';
      type = types.bool;
    };
    showLanguage = mkOption {
      default = true;
      description = ''Show repository language'';
      type = types.bool;
    };
    showStars = mkOption {
      default = true;
      description = ''Show repository stars'';
      type = types.bool;
    };
  };
  globalBadges = {
    enable = mkEnableOption ''Adds global badges from other client mods (Equicord-only)'';
    apiUrl = mkOption {
      default = "https://badges.equicord.org/";
      description = ''API to use'';
      type = types.str;
    };
    showAero = mkOption {
      default = true;
      description = ''Show Aero Badges'';
      type = types.bool;
    };
    showAliucord = mkOption {
      default = true;
      description = ''Show Aliucord Badges'';
      type = types.bool;
    };
    showCustom = mkOption {
      default = true;
      description = ''Show Custom Badges'';
      type = types.bool;
    };
    showEnmity = mkOption {
      default = true;
      description = ''Show Enmity Badges'';
      type = types.bool;
    };
    showNekocord = mkOption {
      default = true;
      description = ''Show Nekocord Badges'';
      type = types.bool;
    };
    showPrefix = mkOption {
      default = true;
      description = ''Shows the Mod as Prefix'';
      type = types.bool;
    };
    showRa1ncord = mkOption {
      default = true;
      description = ''Show Ra1ncord Badges'';
      type = types.bool;
    };
    showReviewDb = mkOption {
      default = true;
      description = ''Show ReviewDB Badges'';
      type = types.bool;
    };
    showSuffix = mkOption {
      default = false;
      description = ''Shows the Mod as Suffix'';
      type = types.bool;
    };
    showVelocity = mkOption {
      default = true;
      description = ''Show Velocity Badges'';
      type = types.bool;
    };
  };
  googleThat = {
    enable = mkEnableOption ''Adds a command to send a internet search link (Equicord-only)'';
    customEngineUrl = mkOption {
      default = null;
      description = ''The URL of the Engine you wish to use'';
      type = types.nullOr types.str;
    };
    defaultEngine = mkOption {
      default = "Google";
      description = ''The search engine to use'';
      type = types.enum [
        "Google"
        "Bing"
        "Yahoo"
        "DuckDuckGo"
        "Baidu"
        "Yandex"
        "Ecosia"
        "Ask"
        "AOL"
        "LetMeGoogleThatForYou"
      ];
    };
    hyperlink = mkOption {
      default = false;
      description = ''If the sent link should hyperlink with the query as the label'';
      type = types.bool;
    };
  };
  guildPickerDumper = {
    enable = mkEnableOption ''Context menu to dump and download a server's emojis and stickers. (Equicord-only)'';
  };
  guildTagSettings = {
    enable = mkEnableOption ''Settings for Guild Tags (Equicord-only)'';
    disableAdoptTagPrompt = mkOption {
      default = true;
      description = ''Disable the prompt to adopt tags (restart required)'';
      type = types.bool;
    };
    hideTags = mkOption {
      default = false;
      description = ''Hide tags'';
      type = types.bool;
    };
  };
  hideChatButtons = {
    enable = mkEnableOption ''able to hide the chat buttons (Equicord-only)'';
    color = mkOption {
      default = false;
      description = ''Color it red on open'';
      type = types.bool;
    };
    open = mkOption {
      default = false;
      description = ''opened by default'';
      type = types.bool;
    };
  };
  hideServers = {
    enable = mkEnableOption ''Allows you to hide servers from the guild list and quick switcher by right clicking them (Equicord-only)'';
  };
  holyNotes = {
    enable = mkEnableOption ''Holy Notes allows you to save messages (Equicord-only)'';
  };
  homeTyping = {
    enable = mkEnableOption ''Changes the home button to a typing indicator if someone in your dms is typing (Equicord-only)'';
  };
  hopOn = {
    enable = mkEnableOption ''Hop on Fortnite or Hop on bloons :3 (Equicord-only)'';
    regex = mkOption {
      default = "hop on (?:fortnite|fn)";
      description = ''Regex to trigger on'';
      type = types.str;
    };
    url = mkOption {
      default = "com.epicgames.launcher://apps/fn%3A4fe75bbc5a674f4f9b356b5c90567da5%3AFortnite?action=launch&silent=true";
      description = ''URL to open'';
      type = types.str;
    };
  };
  husk = {
    enable = mkEnableOption ''Adds Husk button (check settings to change used emoji) (Equicord-only)'';
    emojiId = mkOption {
      default = 1026532993923293184;
      description = ''Emoji ID (default (from Vencord Server): 1026532993923293184)'';
      type = types.int;
    };
    emojiName = mkOption {
      default = "husk";
      description = ''Emoji name (default (from Vencord Server): husk)'';
      type = types.str;
    };
    findInServer = mkOption {
      default = true;
      description = ''Attempt to find emoji of same name in server before using ID in settings (useful if no nitro)'';
      type = types.bool;
    };
  };
  iRememberYou = {
    enable = mkEnableOption ''Locally saves everyone you've been communicating with (including servers), in case of lose (Equicord-only)'';
  };
  iconViewer = {
    enable = mkEnableOption ''Adds a new tab to settings, to preview all icons (Equicord-only)'';
  };
  ignoreCalls = {
    enable = mkEnableOption ''Allows you to ignore calls from specific users or dm groups. (Equicord-only)'';
    permanentlyIgnoredUsers = mkOption {
      default = "";
      description = ''User IDs (comma + space) who should be permanetly ignored (restart required)'';
      type = types.str;
    };
  };
  ignoreTerms = {
    enable = mkEnableOption ''Ignore Discord's new terms of service (Equicord-only)'';
  };
  imgToGif = {
    enable = mkEnableOption ''Adds a /imgtogif slash command to create a gif from any image (Equicord-only)'';
  };
  inRole = {
    enable = mkEnableOption ''Know who is in a role with the role context menu or /inrole command (read plugin info!) (Equicord-only)'';
  };
  ingtoninator = {
    enable = mkEnableOption ''Suffixes 'ington' to a random word in your message (Equicord-only)'';
    isEnabled = mkOption {
      default = true;
      description = ''Enable or disable the Ingtoninator'';
      type = types.bool;
    };
    showIcon = mkOption {
      default = true;
      description = ''Show a button to toggle the Ingtoninator plugin (restart required)'';
      type = types.bool;
    };
  };
  instantScreenshare = {
    enable = mkEnableOption ''Instantly screenshare when joining a voice channel with support for desktop sources, windows, and video input devices (cameras, capture cards) (Equicord-only)'';
  };
  invisibleChat = {
    enable = mkEnableOption ''Encrypt your Messages in a non-suspicious way! (Equicord-only)'';
    savedPasswords = mkOption {
      default = "password, Password";
      description = ''Saved Passwords (Seperated with a , )'';
      type = types.str;
    };
  };
  inviteDefaults = {
    enable = mkEnableOption ''Allows you to edit the default values when creating server invites. (Equicord-only)'';
    inviteDuration = mkOption {
      default = 0;
      description = ''
        Invite Duration

        Values: 1800 = 30 minutes, 3600 = 1 hour, 21600 = 6 hours, 43200 = 12 hours, 86400 = 1 day, 604800 = 7 days, 0 = Forever'';
      type = types.enum [
        1800
        3600
        21600
        43200
        86400
        604800
        0
      ];
    };
    maxUses = mkOption {
      default = 0;
      description = ''
        Invite Use Count

        Values: 0 = Infinite, 1 = 1, 5 = 5, 10 = 10, 25 = 25, 50 = 50, 100 = 100'';
      type = types.enum [
        0
        1
        5
        10
        25
        50
        100
      ];
    };
    temporaryMembership = mkOption {
      default = false;
      description = ''Temporary Membership'';
      type = types.bool;
    };
  };
  jellyfinRichPresence = {
    enable = mkEnableOption ''Rich presence for Jellyfin media server (Equicord-only)'';
    apiKey = mkOption {
      default = null;
      description = ''Jellyfin API key obtained from your Jellyfin administration dashboard'';
      type = types.nullOr types.str;
    };
    coverType = mkOption {
      default = "series";
      description = ''Choose which cover to display when watching a TV show'';
      type = types.enum [
        "series"
        "episode"
      ];
    };
    customName = mkOption {
      default = null;
      description = ''
        Custom Rich Presence name (only used if 'Custom' is selected).
        Options: {name}, {series}, {season}, {episode}, {artist}, {album}, {year}'';
      type = types.nullOr types.str;
    };
    episodeFormat = mkOption {
      default = "long";
      description = ''Episode number format'';
      type = types.enum [
        "long"
        "short"
        "fulltext"
      ];
    };
    nameDisplay = mkOption {
      default = "default";
      description = ''Choose how the application name should appear in Rich Presence'';
      type = types.enum [
        "default"
        "full"
        "custom"
      ];
    };
    overrideRichPresenceType = mkOption {
      default = false;
      description = ''Override the rich presence type'';
      type = types.enum [
        false
        2
        0
        1
        3
      ];
    };
    privacyMode = mkOption {
      default = false;
      description = ''Privacy Mode (Hide media details like Episode/Song Name)'';
      type = types.bool;
    };
    serverUrl = mkOption {
      default = null;
      description = ''Jellyfin server URL (e.g., https://jellyfin.example.com)'';
      type = types.nullOr types.str;
    };
    showEpisodeName = mkOption {
      default = false;
      description = ''Show episode name after season/episode info'';
      type = types.bool;
    };
    showPausedState = mkOption {
      default = true;
      description = ''Show Rich Presence when media is paused'';
      type = types.bool;
    };
    showTmdbButton = mkOption {
      default = true;
      description = ''Show TheMovieDB button in Rich Presence'';
      type = types.bool;
    };
    userId = mkOption {
      default = null;
      description = ''Jellyfin user ID obtained from your user profile URL'';
      type = types.nullOr types.str;
    };
  };
  jumpTo = {
    enable = mkEnableOption ''Adds context menu options to jump to the start or bottom of a channel/DM (Equicord-only)'';
  };
  jumpscare = {
    enable = mkEnableOption ''Adds a configurable chance of jumpscaring you whenever you open a channel. Inspired by Geometry Dash Mega Hack (Equicord-only)'';
    audioSource = mkOption {
      default = "https://github.com/Equicord/Equibored/raw/main/sounds/jumpscare/trollolol.mp3?raw=true";
      description = ''Sets the audio url of the jumpscare'';
      type = types.str;
    };
    chance = mkOption {
      default = 1000;
      description = ''The chance of a jumpscare happening (1 in X so: 100 = 1/100 or 1%, 50 = 1/50 or 2%, etc.)'';
      type = types.int;
    };
    imageSource = mkOption {
      default = "https://github.com/Equicord/Equibored/blob/main/icons/jumpscare/troll.gif?raw=true";
      description = ''Sets the image url of the jumpscare'';
      type = types.str;
    };
  };
  keyboardNavigation = {
    enable = mkEnableOption ''Allows you to navigate the UI with a keyboard. (Equicord-only)'';
    allowMouseControl = mkOption {
      default = true;
      description = ''Allow the mouse to control the command palette.'';
      type = types.bool;
    };
    hotkey = mkOption {
      default = [ ];
      description = ''The hotkey to open the command palette.'';
      type = types.listOf types.str;
    };
  };
  keyboardSounds = {
    enable = mkEnableOption ''Adds OperaGX or osu! sound effects when typing on your keyboard. (Equicord-only)'';
    soundPack = mkOption {
      default = "operagx";
      description = ''Sound pack to use.'';
      type = types.enum [
        "operagx"
        "osu"
      ];
    };
    volume = mkOption {
      default = 100.0;
      description = ''Volume of the keyboard sounds.'';
      type = types.float;
    };
  };
  keywordNotify = {
    enable = mkEnableOption ''Sends a notification if a given message matches certain keywords or regexes (Equicord-only)'';
    amountToKeep = mkOption {
      default = 50;
      description = ''Amount of messages to keep in the log'';
      type = types.int;
    };
    ignoreBots = mkOption {
      default = true;
      description = ''Ignore messages from bots'';
      type = types.bool;
    };
    keywords = mkOption {
      default = { };
      description = ''Manage keywords'';
      type = types.attrs;
    };
  };
  lastActive = {
    enable = mkEnableOption ''A plugin to jump to last active message from yourself or another user in a channel/server. (Equicord-only)'';
  };
  limitMiddleClickPaste = {
    enable = mkEnableOption ''For middle-click autoscroll users, prevents middle-click from making unwanted pastes. (Equicord-only)'';
    limitTo = mkOption {
      default = "active";
      description = ''Allow middle click pastes:'';
      type = types.enum [
        "active"
        "direct"
        "never"
      ];
    };
    reenableDelay = mkOption {
      default = 500.0;
      description = ''Milliseconds until re-enabling global paste events after middle click.'';
      type = types.float;
    };
  };
  listenBrainzRpc = {
    enable = mkEnableOption ''Little plugin for ListenBrainz rich presence (Equicord-only)'';
    hideWithActivity = mkOption {
      default = false;
      description = ''hide ListenBrainz presence if you have any other presence'';
      type = types.bool;
    };
    hideWithSpotify = mkOption {
      default = true;
      description = ''hide ListenBrainz presence if Spotify is running'';
      type = types.bool;
    };
    mbContact = mkOption {
      default = null;
      description = ''ListenBrainz contact'';
      type = types.nullOr types.str;
    };
    missingArt = mkOption {
      default = "listenbrainzLogo";
      description = ''When album or album art is missing'';
      type = types.enum [
        "listenbrainzLogo"
        "placeholder"
      ];
    };
    nameFormat = mkOption {
      default = "status-name";
      description = ''Show name of song and artist in status name'';
      type = types.enum [
        "status-name"
        "artist-first"
        "song-first"
        "artist"
        "song"
        "album"
      ];
    };
    shareSong = mkOption {
      default = true;
      description = ''show link to song on ListenBrainz (may only be visible to other users)'';
      type = types.bool;
    };
    shareUsername = mkOption {
      default = false;
      description = ''show link to ListenBrainz profile (may only be visible to other users)'';
      type = types.bool;
    };
    statusName = mkOption {
      default = "some music";
      description = ''custom status text'';
      type = types.str;
    };
    useListeningStatus = mkOption {
      default = true;
      description = ''show "Listening to" status instead of "Playing"'';
      type = types.bool;
    };
    useLogo = mkOption {
      default = true;
      description = ''Show ListenBrainz logo on album art'';
      type = types.bool;
    };
    useTimeBar = mkOption {
      default = true;
      description = ''use track duration to display a time bar (must be using Listening status)'';
      type = types.bool;
    };
    username = mkOption {
      default = null;
      description = ''ListenBrainz username'';
      type = types.nullOr types.str;
    };
  };
  loginWithQr = {
    enable = mkEnableOption ''Allows you to login to another device by scanning a login QR code, just like on mobile! (Equicord-only)'';
    scanQr = mkOption {
      default = { };
      description = ''Scan a QR code'';
      type = types.attrs;
    };
  };
  mediaPlaybackSpeed = {
    enable = mkEnableOption ''Allows changing the (default) playback speed of media embeds (Equicord-only)'';
    defaultAudioSpeed = mkOption {
      default = 1.0;
      description = ''Audios'';
      type = types.float;
    };
    defaultVideoSpeed = mkOption {
      default = 1.0;
      description = ''Videos'';
      type = types.float;
    };
    defaultVoiceMessageSpeed = mkOption {
      default = 1.0;
      description = ''Voice messages'';
      type = types.float;
    };
  };
  messageBurst = {
    enable = mkEnableOption ''Merges messages sent within a time period with your previous sent message if no one else sends a message before you. (Equicord-only)'';
    shouldMergeWithAttachment = mkOption {
      default = false;
      description = ''Should the message be merged if the last message has an attachment?'';
      type = types.bool;
    };
    timePeriod = mkOption {
      default = 3;
      description = ''The duration of bursts (in seconds).'';
      type = types.int;
    };
    useSpace = mkOption {
      default = false;
      description = ''Whether to add a space between messages when merging instead of new lines.'';
      type = types.bool;
    };
  };
  messageColors = {
    enable = mkEnableOption ''Displays color codes like #FF0042 inside of messages (Equicord-only)'';
  };
  messageFetchTimer = {
    enable = mkEnableOption ''Shows how long it took to fetch messages for the current channel (Equicord-only)'';
    iconColor = mkOption {
      default = "#00d166";
      description = ''Icon color (CSS color value)'';
      type = types.str;
    };
    showIcon = mkOption {
      default = true;
      description = ''Show fetch time icon in message bar'';
      type = types.bool;
    };
    showMs = mkOption {
      default = true;
      description = ''Show milliseconds in timing'';
      type = types.bool;
    };
  };
  messageLinkTooltip = {
    enable = mkEnableOption ''Like MessageLinkEmbed but without taking space (Equicord-only)'';
    display = mkOption {
      default = "auto";
      description = ''Display style'';
      type = types.enum [
        "auto"
        "compact"
        "cozy"
      ];
    };
    onForward = mkOption {
      default = true;
      description = ''Show tooltip when hovering over forwarded messages (restart required)'';
      type = types.bool;
    };
    onLink = mkOption {
      default = true;
      description = ''Show tooltip when hovering over message links (restart required)'';
      type = types.bool;
    };
    onReply = mkOption {
      default = true;
      description = ''Show tooltip when hovering over message replies (restart required)'';
      type = types.bool;
    };
  };
  messageLoggerEnhanced = {
    enable = mkEnableOption ''G'day (Equicord-only)'';
  };
  messageNotifier = {
    enable = mkEnableOption ''Get toasts for when chosen users send a message (Equicord-only)'';
    users = mkOption {
      default = "";
      description = ''Comma separated list of user ids to get message toasts for'';
      type = types.str;
    };
  };
  messageTranslate = {
    enable = mkEnableOption ''Auto translate messages to your language (Equicord-only)'';
    confidenceRequirement = mkOption {
      default = "0.8";
      description = ''The confidence required to translated the message. Best not to edit unless you know what you're doing (restart required)'';
      type = types.str;
    };
    targetLanguage = mkOption {
      default = "en";
      description = ''The language messages should be translated to (restart required)'';
      type = types.str;
    };
  };
  moreCommands = {
    enable = mkEnableOption ''Adds various fun and useful commands (Equicord-only)'';
  };
  moreKaomoji = {
    enable = mkEnableOption ''Adds more Kaomoji to discord. ヽ(´▽`)/ (Equicord-only)'';
  };
  moreStickers = {
    enable = mkEnableOption ''Adds sticker packs from other social media platforms. (e.g. LINE) (Equicord-only)'';
    packs = mkOption {
      default = { };
      description = ''Packs'';
      type = types.attrs;
    };
  };
  moreUserTags = {
    enable = mkEnableOption ''Adds tags for webhooks and moderative roles (owner, admin, etc.) (Equicord-only)'';
  };
  moyai = {
    enable = mkEnableOption ''🗿🗿🗿🗿🗿🗿🗿🗿 (Equicord-only)'';
    ignoreBlocked = mkOption {
      default = true;
      description = ''Ignore blocked users'';
      type = types.bool;
    };
    ignoreBots = mkOption {
      default = true;
      description = ''Ignore bots'';
      type = types.bool;
    };
    quality = mkOption {
      default = "Normal";
      description = ''Quality of the 🗿🗿🗿'';
      type = types.enum [
        "Normal"
        "HD"
      ];
    };
    triggerWhenUnfocused = mkOption {
      default = true;
      description = ''Trigger the 🗿 even when the window is unfocused'';
      type = types.bool;
    };
    volume = mkOption {
      default = 0.5;
      description = ''Volume of the 🗿🗿🗿'';
      type = types.float;
    };
  };
  musicControls = {
    enable = mkEnableOption ''Music Controls and Lyrics for multiple services  (Equicord-only)'';
  };
  neverPausePreviews = {
    enable = mkEnableOption ''Prevents in-call/PiP previews (screenshare, streams, etc) from pausing even if the client loses focus (Equicord-only)'';
  };
  newPluginsManager = {
    enable = mkEnableOption ''Utility that notifies you when new plugins are added to Equicord (Equicord-only)'';
  };
  noAppsAllowed = {
    enable = mkEnableOption ''returns the bot's tag :skulk: (Equicord-only)'';
  };
  noBulletPoints = {
    enable = mkEnableOption ''Stops you from typing markdown bullet points (stinky) (Equicord-only)'';
  };
  noModalAnimation = {
    enable = mkEnableOption ''Remove the 300ms long animation when opening or closing modals (Equicord-only)'';
  };
  noNitroUpsell = {
    enable = mkEnableOption ''Removes ALL of Discord's nitro upsells by tricking the client into thinking you have nitro. (Equicord-only)'';
  };
  noRoleHeaders = {
    enable = mkEnableOption ''We are all equal!! (Equicord-only)'';
  };
  noRpc = {
    enable = mkEnableOption ''Disables Discord's RPC server. (Equicord-only)'';
  };
  notificationTitle = {
    enable = mkEnableOption ''Makes desktop notifications more informative (Equicord-only)'';
  };
  orbolayBridge = {
    enable = mkEnableOption ''Bridge plugin to connect Orbolay to Discord (Equicord-only)'';
    isKeybindEnabled = mkOption {
      default = true;
      description = ''Enable/disable the global keybind (Ctrl + `) (restart required)'';
      type = types.bool;
    };
    messageAlignment = mkOption {
      default = "topright";
      description = ''Alignment of messages in the overlay (restart required)'';
      type = types.enum [
        "topleft"
        "topright"
        "bottomleft"
        "bottomright"
      ];
    };
    messagesSemitransparent = mkOption {
      default = false;
      description = ''Make message notifications transparent (restart required)'';
      type = types.bool;
    };
    port = mkOption {
      default = 6888;
      description = ''Port to connect to (restart required)'';
      type = types.int;
    };
    userAlignment = mkOption {
      default = "topleft";
      description = ''Alignment of users in the overlay (restart required)'';
      type = types.enum [
        "topleft"
        "topright"
        "bottomleft"
        "bottomright"
      ];
    };
    voiceSemitransparent = mkOption {
      default = true;
      description = ''Make voice channel members transparent (restart required)'';
      type = types.bool;
    };
  };
  partyMode = {
    enable = mkEnableOption ''Allows you to use party mode cause the party never ends ✨ (Equicord-only)'';
    superIntensePartyMode = mkOption {
      default = 0;
      description = ''
        Party intensity

        Values: 0 = Normal, 1 = Better, 2 = Project X'';
      type = types.enum [
        0
        1
        2
      ];
    };
  };
  pinIcon = {
    enable = mkEnableOption ''Adds a pin icon to pinned messages (Equicord-only)'';
  };
  pingNotifications = {
    enable = mkEnableOption ''Customizable notifications with improved mention formatting (Equicord-only)'';
    dms = mkOption {
      default = true;
      description = ''Notify for direct messages (DMs)'';
      type = types.bool;
    };
    friends = mkOption {
      default = false;
      description = ''Notify when friends send messages in servers'';
      type = types.bool;
    };
    ignoreMuted = mkOption {
      default = true;
      description = ''Skip notifications from muted servers, channels, or users'';
      type = types.bool;
    };
    mentions = mkOption {
      default = true;
      description = ''Notify when someone @mentions you directly'';
      type = types.bool;
    };
    showInActive = mkOption {
      default = false;
      description = ''Show notifications even for currently active channel'';
      type = types.bool;
    };
  };
  platformSpoofer = {
    enable = mkEnableOption ''Spoof what platform or device you're on (Equicord-only)'';
    platform = mkOption {
      default = "desktop";
      description = ''What platform to show up as on (restart required)'';
      type = types.enum [
        "desktop"
        "web"
        "android"
        "ios"
        "xbox"
        "playstation"
      ];
    };
  };
  polishWording = {
    enable = mkEnableOption ''Tweaks your messages to make them look nicer and have better grammar. See settings (Equicord-only)'';
    blockedWords = mkOption {
      default = "";
      description = ''Words that will not be capitalized (comma separated).'';
      type = types.str;
    };
    expandContractions = mkOption {
      default = false;
      description = ''Expand contractions.'';
      type = types.bool;
    };
    fixApostrophes = mkOption {
      default = true;
      description = ''Ensure contractions contain apostrophes.'';
      type = types.bool;
    };
    fixCapitalization = mkOption {
      default = false;
      description = ''Capitalize sentences.'';
      type = types.bool;
    };
    fixPunctuation = mkOption {
      default = false;
      description = ''Punctate sentences.'';
      type = types.bool;
    };
    fixPunctuationFrequency = mkOption {
      default = 100.0;
      description = ''Percent period frequency (this majorly annoys some people).'';
      type = types.float;
    };
    quickDisable = mkOption {
      default = false;
      description = ''Quick disable. Turns off message modifying without requiring a client reload.'';
      type = types.bool;
    };
  };
  questCompleter = {
    enable = mkEnableOption ''A plugin to complete quests without having the game installed. (Equicord-only)'';
    disableNotifications = mkOption {
      default = false;
      description = ''Disable notifications when no quests are available or when a quest is completed'';
      type = types.bool;
    };
  };
  questFocused = {
    enable = mkEnableOption ''Prevent the quests player from pausing and possibly skip it all together. (Equicord-only)'';
  };
  questify = {
    enable = mkEnableOption ''Enhance your Quest experience with a suite of features, or disable them entirely if they're not your thing. (Equicord-only)'';
  };
  questionMarkReplacement = {
    enable = mkEnableOption ''Replace all question marks with chosen string, if message only contains question marks. (Equicord-only)'';
    replace = mkOption {
      default = ":face_with_monocle:";
      description = ''Replace with'';
      type = types.str;
    };
  };
  quickThemeSwitcher = {
    enable = mkEnableOption ''Quickly switch between themes using keyboard shortcuts. (Equicord-only)'';
    autoRefresh = mkOption {
      default = true;
      description = ''Auto-refresh theme list when changes are detected'';
      type = types.bool;
    };
    includeLocal = mkOption {
      default = true;
      description = ''Include local themes'';
      type = types.bool;
    };
    includeOnline = mkOption {
      default = true;
      description = ''Include online themes'';
      type = types.bool;
    };
    showNotifications = mkOption {
      default = true;
      description = ''Show notifications when themes are added/removed'';
      type = types.bool;
    };
    sortOrder = mkOption {
      default = "alphabetical";
      description = ''Sort method'';
      type = types.enum [
        "alphabetical"
        "reverse"
        "recent"
      ];
    };
  };
  quoter = {
    enable = mkEnableOption ''Adds the ability to create an inspirational quote image from a message. (Equicord-only)'';
    quoteFont = mkOption {
      default = "M PLUS Rounded 1c";
      description = ''Font for quote text (author/username always use M PLUS Rounded 1c)'';
      type = types.enum [
        "M PLUS Rounded 1c"
        "Open Sans"
        "Momo Signature"
        "Lora"
        "Merriweather"
      ];
    };
    watermark = mkOption {
      default = "Made with Equicord";
      description = ''Custom watermark text (max 32 characters)'';
      type = types.str;
    };
  };
  randomVoice = {
    enable = mkEnableOption ''Adds a Button near the Mute button to join a random voice call. (Equicord-only)'';
    autoCamera = mkOption {
      default = false;
      description = ''Automatically turns on camera'';
      type = types.bool;
    };
    autoNavigate = mkOption {
      default = false;
      description = ''Automatically navigates to the voice-channel.'';
      type = types.bool;
    };
    autoStream = mkOption {
      default = false;
      description = ''Automatically turns on stream'';
      type = types.bool;
    };
    avoidAfk = mkOption {
      default = false;
      description = ''Avoids joining AFK voice-channels.'';
      type = types.bool;
    };
    avoidStages = mkOption {
      default = false;
      description = ''Avoids joining stage voice-channels.'';
      type = types.bool;
    };
    avoidStates = mkOption {
      default = false;
      description = ''Option to avoid states'';
      type = types.bool;
    };
    deafen = mkOption {
      default = false;
      description = ''Searches for users who are deafened'';
      type = types.bool;
    };
    includeStates = mkOption {
      default = false;
      description = ''Option to include states'';
      type = types.bool;
    };
    leaveEmpty = mkOption {
      default = false;
      description = ''Finds a random-call, when the voice chat is empty.'';
      type = types.bool;
    };
    mute = mkOption {
      default = false;
      description = ''Searches for users who are muted'';
      type = types.bool;
    };
    selfDeafen = mkOption {
      default = false;
      description = ''Automatically deafems your mic when joining voice-channel.'';
      type = types.bool;
    };
    selfMute = mkOption {
      default = false;
      description = ''Automatically mutes your mic when joining voice-channel.'';
      type = types.bool;
    };
    servers = mkOption {
      default = "";
      description = ''Servers that are included'';
      type = types.str;
    };
    spacesLeft = mkOption {
      default = 3.0;
      description = ''Select amount of max users'';
      type = types.float;
    };
    spacesLeftOperation = mkOption {
      default = "==";
      description = ''Select an operation for the maximum amounts of users'';
      type = types.enum [
        "<"
        ">"
        "=="
      ];
    };
    stream = mkOption {
      default = false;
      description = ''Searches for users who are streaming'';
      type = types.bool;
    };
    userAmount = mkOption {
      default = 3.0;
      description = ''Select amount of users'';
      type = types.float;
    };
    userAmountOperation = mkOption {
      default = "==";
      description = ''Select an operation for the amounts of users'';
      type = types.enum [
        "<"
        ">"
        "=="
      ];
    };
    vcLimit = mkOption {
      default = 5.0;
      description = ''Select a voice-channel limit'';
      type = types.float;
    };
    vcLimitOperation = mkOption {
      default = "==";
      description = ''Select an operation for the voice-channel.'';
      type = types.enum [
        "<"
        ">"
        "=="
      ];
    };
    video = mkOption {
      default = false;
      description = ''Searches for users with their video on'';
      type = types.bool;
    };
  };
  recentDmSwitcher = {
    enable = mkEnableOption ''Ctrl+Tab between most recently used DMs (Ctrl+Shift+Tab reverse) (Equicord-only)'';
    amountOfUsers = mkOption {
      default = 20.0;
      description = ''Number of users to show in overlay'';
      type = types.float;
    };
    clearRdms = mkOption {
      default = { };
      description = ''Testing utility: Clear RDMS list'';
      type = types.attrs;
    };
    overlayMode = mkOption {
      default = "row";
      description = ''Overlay content'';
      type = types.enum [
        "row"
        "current"
      ];
    };
    overlayRowLength = mkOption {
      default = 5.0;
      description = ''Number of recent DMs to show in row'';
      type = types.float;
    };
    overlayShowAvatars = mkOption {
      default = true;
      description = ''Show avatars in overlay'';
      type = types.bool;
    };
    toastDurationMs = mkOption {
      default = 600.0;
      description = ''Toast hide delay (ms)'';
      type = types.float;
    };
    visualStyle = mkOption {
      default = "overlay";
      description = ''Visual indicator style while cycling'';
      type = types.enum [
        "overlay"
        "toast"
        "off"
      ];
    };
  };
  remixRevived = {
    enable = mkEnableOption ''Revives Remix and breings it to Desktop (Equicord-only)'';
  };
  repeatMessages = {
    enable = mkEnableOption ''Allows you to repeat messages quickly. If you hold shift while clicking the Repeat option, it will reply to the message. (Equicord-only)'';
  };
  replyPingControl = {
    enable = mkEnableOption ''Control whether to always or never get pinged on message replies, with a whitelist feature (Equicord-only)'';
    alwaysPingOnReply = mkOption {
      default = false;
      description = ''Always get pinged when someone replies to your messages'';
      type = types.bool;
    };
    replyPingWhitelist = mkOption {
      default = "";
      description = ''Comma-separated list of User IDs to always receive reply pings from'';
      type = types.str;
    };
  };
  richMagnetLinks = {
    enable = mkEnableOption ''Renders magnet links like message links (Equicord-only)'';
  };
  rpcEditor = {
    enable = mkEnableOption ''Edit the type and content of any Rich Presence (Equicord-only)'';
    replacedAppIds = mkOption {
      default = { };
      type = types.attrs;
    };
  };
  rpcStats = {
    enable = mkEnableOption ''Displays stats about your activity as an rpc (Equicord-only)'';
    albumCoverImage = mkOption {
      default = true;
      description = ''Should the album cover image be used as the rpc image? (if you have the last fm display chosen)'';
      type = types.bool;
    };
    assetUrl = mkOption {
      default = "";
      description = ''The image to use for your rpc. Your profile picture is used if left blank'';
      type = types.str;
    };
    lastFmApiKey = mkOption {
      default = "";
      description = ''Your last.fm API key'';
      type = types.str;
    };
    lastFmStatFormat = mkOption {
      default = "Top album this week: \"$album - $artist\"";
      description = ''How should the last fm stat be formatted? ''$album is replaced with the album name, and ''$artist is replaced with the artist name'';
      type = types.str;
    };
    lastFmUsername = mkOption {
      default = "";
      description = ''Your last.fm username'';
      type = types.str;
    };
    rpcTitle = mkOption {
      default = "RPCStats";
      description = ''The title for the rpc'';
      type = types.str;
    };
    statDisplay = mkOption {
      default = 0;
      description = ''
        What should the rpc display? (you can only have one line i'm pretty sure)

        Values: 0 = The amount of messages sent today, 1 = The amount of messages sent all time, 2 = Your most listened album for the week'';
      type = types.enum [
        0
        1
        2
      ];
    };
  };
  saveFavoriteGiFs = {
    enable = mkEnableOption ''Save favorite GIF urls to a file (Equicord-only)'';
  };
  screenRecorder = {
    enable = mkEnableOption ''epic screen recorder lol (Equicord-only)'';
  };
  searchFix = {
    enable = mkEnableOption ''Fixes the annoying "We dropped the magnifying glass!" error. (Equicord-only)'';
  };
  sekaiStickers = {
    enable = mkEnableOption ''Sekai Stickers built in discord originally from github.com/TheOriginalAyaka (Equicord-only)'';
    autoCloseModal = mkOption {
      default = true;
      description = ''Auto close modal when done'';
      type = types.bool;
    };
  };
  selfForward = {
    enable = mkEnableOption ''adds the current channel to the forward list popup (Equicord-only)'';
  };
  serverSearch = {
    enable = mkEnableOption ''Navigate your servers better with a quick search button (Equicord-only)'';
  };
  showBadgesInChat = {
    enable = mkEnableOption ''Shows the message author's badges beside their name in chat. (Equicord-only)'';
  };
  showMessageEmbeds = {
    enable = mkEnableOption ''Adds a context menu option to show embeds for links that don't have one (Equicord-only)'';
  };
  showResourceChannels = {
    enable = mkEnableOption ''shows the channels hidden behind the server resources in the channel list (Equicord-only)'';
  };
  sidebarChat = {
    enable = mkEnableOption ''Open a another channel or a DM as a sidebar or as a popout (Equicord-only)'';
  };
  signature = {
    enable = mkEnableOption ''Automated fingerprint/end text (Equicord-only)'';
    contextMenu = mkOption {
      default = true;
      description = ''Add option to toggle the functionality in the chat input context menu'';
      type = types.bool;
    };
    isEnabled = mkOption {
      default = true;
      description = ''Toggle functionality'';
      type = types.bool;
    };
    name = mkOption {
      default = "a chronic discord user";
      description = ''The signature that will be added to the end of your messages'';
      type = types.str;
    };
    showIcon = mkOption {
      default = true;
      description = ''Show an icon for toggling the plugin in the chat bar (restart required)'';
      type = types.bool;
    };
    textHeader = mkOption {
      default = ">";
      description = ''What header to preface text with'';
      type = types.str;
    };
  };
  snowfall = {
    enable = mkEnableOption ''Let it snow on Discord! Ported from the BetterDiscord plugin by square. (Equicord-only)'';
    flakesPerSecond = mkOption {
      default = 5.0;
      description = ''Snowflakes per second (higher = denser snowfall)'';
      type = types.float;
    };
    maxSize = mkOption {
      default = 30.0;
      description = ''Maximum snowflake size'';
      type = types.float;
    };
    speed = mkOption {
      default = 50.0;
      description = ''Snowfall speed (higher = faster fall)'';
      type = types.float;
    };
    typeOfSnow = mkOption {
      default = "text";
      description = ''Change the type of snow displayed (Affects performance).'';
      type = types.enum [
        "solid"
        "text"
        "image"
      ];
    };
  };
  soggy = {
    enable = mkEnableOption ''Adds a soggy button to the toolbox (Equicord-only)'';
    boopLink = mkOption {
      default = "https://github.com/Equicord/Equibored/raw/main/sounds/soggy/honk.wav?raw=true";
      description = ''URL for the boop sound'';
      type = types.str;
    };
    boopVolume = mkOption {
      default = 0.2;
      description = ''Volume of the boop sound'';
      type = types.float;
    };
    imageLink = mkOption {
      default = "https://images.equicord.org/api/files/raw/0199e730-70d5-7000-a44f-d1acb42064cc";
      description = ''URL for the image (button and modal)'';
      type = types.str;
    };
    songLink = mkOption {
      default = "https://github.com/Equicord/Equibored/raw/main/sounds/soggy/song.mp3?raw=true";
      description = ''URL for the song to play'';
      type = types.str;
    };
    songVolume = mkOption {
      default = 0.25;
      description = ''Volume of the song. 0 to disable'';
      type = types.float;
    };
    tooltipText = mkOption {
      default = "the soggy";
      description = ''The text shown when hovering over the button'';
      type = types.str;
    };
  };
  songLink = {
    enable = mkEnableOption ''Adds streaming service buttons below song links (Equicord-only)'';
    servicesComponent = mkOption {
      default = { };
      type = types.attrs;
    };
    servicesSettings = mkOption {
      default = { };
      description = ''settings for services'';
      type = types.attrs;
    };
    userCountry = mkOption {
      default = "US";
      description = ''Country used for lookup (Two letter country code)'';
      type = types.str;
    };
  };
  soundBoardLogger = {
    enable = mkEnableOption ''Logs all soundboards that are played in a voice chat and allows you to download them (Equicord-only)'';
  };
  splitLargeMessages = {
    enable = mkEnableOption ''Splits large messages into multiple to fit Discord's message limit. (Equicord-only)'';
    disableFileConversion = mkOption {
      default = true;
      description = ''If true, disables file conversion for large messages.'';
      type = types.bool;
    };
    hardSplit = mkOption {
      default = false;
      description = ''If true, splits on the last character instead of the last space/newline.'';
      type = types.bool;
    };
    maxLength = mkOption {
      default = 0;
      description = ''Maximum length of a message before it is split. Set to 0 to automatically detect.'';
      type = types.int;
    };
    sendDelay = mkOption {
      default = 1.0;
      description = ''Delay between each chunk in seconds.'';
      type = types.float;
    };
    slowmodeMax = mkOption {
      default = 5;
      description = ''Maximum slowmode time if splitting in slowmode.'';
      type = types.int;
    };
    splitInSlowmode = mkOption {
      default = false;
      description = ''Should messages be split if the channel has slowmode enabled?'';
      type = types.bool;
    };
  };
  spotifyActivityToggle = {
    enable = mkEnableOption ''Adds a toggle button for Spotify activity visibility. (Equicord-only)'';
  };
  statsfmPresence = {
    enable = mkEnableOption ''Statsfm presence to track your music (Equicord-only)'';
    alwaysHideArt = mkOption {
      default = false;
      description = ''Disable downloading album art'';
      type = types.bool;
    };
    hideWithExternalRpc = mkOption {
      default = false;
      description = ''Hides stats.fm presence if an external RPC is running'';
      type = types.bool;
    };
    hideWithSpotify = mkOption {
      default = false;
      description = ''Hide stats.fm presence if spotify is running'';
      type = types.bool;
    };
    missingArt = mkOption {
      default = "StatsFmLogo";
      description = ''When albums or albums art is missing'';
      type = types.enum [
        "StatsFmLogo"
        "placeholder"
      ];
    };
    nameFormat = mkOption {
      default = "status-name";
      description = ''Show name of song and artist in status name'';
      type = types.enum [
        "status-name"
        "artist-first"
        "song-first"
        "artist"
        "song"
        "albums"
      ];
    };
    shareSong = mkOption {
      default = true;
      description = ''Show link to song on stats.fm'';
      type = types.bool;
    };
    shareUsername = mkOption {
      default = false;
      description = ''Show link to stats.fm profile'';
      type = types.bool;
    };
    showStatsFmLogo = mkOption {
      default = true;
      description = ''Show the Stats.fm next to the albums cover'';
      type = types.bool;
    };
    statusName = mkOption {
      default = "Stats.fm";
      description = ''Custom status text'';
      type = types.str;
    };
    useListeningStatus = mkOption {
      default = true;
      description = ''Show "Listening to" status instead of "Playing"'';
      type = types.bool;
    };
    username = mkOption {
      default = null;
      description = ''Stats.fm username'';
      type = types.nullOr types.str;
    };
  };
  statusPresets = {
    enable = mkEnableOption ''Allows you to remember your statuses and set them later (Equicord-only)'';
    statusPresets = mkOption {
      default = { };
      description = ''Status Presets'';
      type = types.attrs;
    };
  };
  statusWhileActive = {
    enable = mkEnableOption ''Automatically updates your online status when in a voice channel. (Equicord-only)'';
    statusToSet = mkOption {
      default = "dnd";
      description = ''Status to set while in a voice channel.'';
      type = types.enum [
        "online"
        "idle"
        "dnd"
        "invisible"
      ];
    };
  };
  steamStatusSync = {
    enable = mkEnableOption ''Sync your status to Steam! (Equicord-only)'';
    dndStatus = mkOption {
      default = "none";
      description = ''Steam status when on Do Not Disturb'';
      type = types.enum [
        "online"
        "away"
        "invisible"
        "offline"
        "none"
      ];
    };
    goInvisibleIfActivityIsHidden = mkOption {
      default = false;
      description = ''Always go invisible if hiding game activity on Discord'';
      type = types.bool;
    };
    idleStatus = mkOption {
      default = "away";
      description = ''Steam status when on Idle'';
      type = types.enum [
        "online"
        "away"
        "invisible"
        "offline"
        "none"
      ];
    };
    invisibleStatus = mkOption {
      default = "invisible";
      description = ''Steam status when on Invisible'';
      type = types.enum [
        "online"
        "away"
        "invisible"
        "offline"
        "none"
      ];
    };
    onlineStatus = mkOption {
      default = "online";
      description = ''Steam status when on Online'';
      type = types.enum [
        "online"
        "away"
        "invisible"
        "offline"
        "none"
      ];
    };
  };
  stickerBlocker = {
    enable = mkEnableOption ''Allows you to block stickers from being displayed. (Equicord-only)'';
    blockedStickers = mkOption {
      default = "";
      description = ''The list of blocked sticker IDs (don't edit unless you know what you're doing)'';
      type = types.str;
    };
    showButton = mkOption {
      default = true;
      description = ''Whether to show a button to unblock the gif (restart required)'';
      type = types.bool;
    };
    showGif = mkOption {
      default = true;
      description = ''Whether to show a snazzy cat gif (restart required)'';
      type = types.bool;
    };
    showMessage = mkOption {
      default = false;
      description = ''Whether to show a message detailing which id was blocked (restart required)'';
      type = types.bool;
    };
  };
  streamingCodecDisabler = {
    enable = mkEnableOption ''Disable codecs for streaming of your choice (Equicord-only)'';
    disableAv1Codec = mkOption {
      default = false;
      description = ''Make Discord not consider using AV1 for streaming.'';
      type = types.bool;
    };
    disableH264Codec = mkOption {
      default = false;
      description = ''Make Discord not consider using H264 for streaming.'';
      type = types.bool;
    };
    disableH265Codec = mkOption {
      default = false;
      description = ''Make Discord not consider using H265 for streaming.'';
      type = types.bool;
    };
    disableVp8Codec = mkOption {
      default = false;
      description = ''Make Discord not consider using VP8 for streaming.'';
      type = types.bool;
    };
    disableVp9Codec = mkOption {
      default = false;
      description = ''Make Discord not consider using VP9 for streaming.'';
      type = types.bool;
    };
  };
  talkInReverse = {
    enable = mkEnableOption ''Reverses the message content before sending it. (Equicord-only)'';
  };
  themeLibrary = {
    enable = mkEnableOption ''A library of themes for Vencord. (Equicord-only)'';
  };
  tidalEmbeds = {
    enable = mkEnableOption ''Embeds TIDAL songs to make them playable in Discord. (Equicord-only)'';
  };
  tiktokTts = {
    enable = mkEnableOption ''Reads out chat messages with the good ol' Tiktok TTS voice :sob: (Equicord-only)'';
  };
  timelessClips = {
    enable = mkEnableOption ''Add a your own clip length (Equicord-only)'';
    clipLength = mkOption {
      default = 5.0;
      description = ''Add clip length option in minutes'';
      type = types.float;
    };
  };
  timezones = {
    enable = mkEnableOption ''Shows the local time of users in profiles and message headers (Equicord-only)'';
    _24hTime = mkOption {
      default = false;
      description = ''Show time in 24h format'';
      type = types.bool;
    };
    databaseUrl = mkOption {
      default = "https://timezone.creations.works";
      description = ''Database URL for timezone storage'';
      type = types.str;
    };
    preferDatabaseOverLocal = mkOption {
      default = true;
      description = ''Prefer database over local storage for timezones'';
      type = types.bool;
    };
    resetDatabaseTimezone = mkOption {
      default = { };
      description = ''Reset your timezone on the database'';
      type = types.attrs;
    };
    setDatabaseTimezone = mkOption {
      default = { };
      description = ''Set your timezone on the database'';
      type = types.attrs;
    };
    showMessageHeaderTime = mkOption {
      default = true;
      description = ''Show time in message headers'';
      type = types.bool;
    };
    showOwnTimezone = mkOption {
      default = true;
      description = ''Show your own timezone in profiles and message headers'';
      type = types.bool;
    };
    showProfileTime = mkOption {
      default = true;
      description = ''Show time in profiles'';
      type = types.bool;
    };
    showTimezoneInfo = mkOption {
      default = true;
      description = ''Show timezone info next to time'';
      type = types.bool;
    };
    useDatabase = mkOption {
      default = true;
      description = ''Enable database for getting user timezones'';
      type = types.bool;
    };
  };
  title = {
    enable = mkEnableOption ''Replaces the window title prefix (Equicord-only)'';
    title = mkOption {
      default = "Equicord";
      description = ''Window title prefix'';
      type = types.str;
    };
  };
  toastNotifications = {
    enable = mkEnableOption ''Show a toast notification whenever you receive a direct message. (Equicord-only)'';
    determineServerNotifications = mkOption {
      default = true;
      description = ''Automatically determine what server notifications to show based on your channel/guild settings'';
      type = types.bool;
    };
    directMessages = mkOption {
      default = true;
      description = ''Show notifications for direct messages'';
      type = types.bool;
    };
    disableInStreamerMode = mkOption {
      default = true;
      description = ''Disable notifications while in streamer mode'';
      type = types.bool;
    };
    exampleButton = mkOption {
      default = { };
      description = ''Show an example toast notification.'';
      type = types.attrs;
    };
    friendActivity = mkOption {
      default = true;
      description = ''Show notifications for adding someone or receiving a friend request'';
      type = types.bool;
    };
    friendServerNotifications = mkOption {
      default = true;
      description = ''Show notifications when friends send messages in servers they share with you'';
      type = types.bool;
    };
    groupMessages = mkOption {
      default = true;
      description = ''Show notifications for group messages'';
      type = types.bool;
    };
    ignoreUsers = mkOption {
      default = "";
      description = ''Create a list of user ids to ignore all their notifications from (separate with commas)'';
      type = types.str;
    };
    maxNotifications = mkOption {
      default = 3.0;
      description = ''Maximum number of notifications displayed at once'';
      type = types.float;
    };
    notifyFor = mkOption {
      default = "";
      description = ''Create a list of channel ids to receive notifications from (separate with commas)'';
      type = types.str;
    };
    opacity = mkOption {
      default = 100.0;
      description = ''Opacity of the notification'';
      type = types.float;
    };
    position = mkOption {
      default = "bottom-left";
      description = ''The position of the toast notification'';
      type = types.enum [
        "bottom-left"
        "top-left"
        "top-right"
        "bottom-right"
      ];
    };
    renderImages = mkOption {
      default = true;
      description = ''Render images in notifications'';
      type = types.bool;
    };
    streamingTreatment = mkOption {
      default = 0;
      description = ''
        How to treat notifications while sharing your screen

        Values: 0 = Normal - Show the notification as normal, 1 = No Content - Hide the notification body, 2 = Ignore - Don't show the notification at all'';
      type = types.enum [
        0
        1
        2
      ];
    };
    timeout = mkOption {
      default = 5.0;
      description = ''Time in seconds notifications will be shown for'';
      type = types.float;
    };
  };
  toggleVideoBind = {
    enable = mkEnableOption ''Adds a customizable bind to toggle webcam. (Equicord-only)'';
    keyBind = mkOption {
      default = "KeyX";
      description = ''The key to toggle webcam when pressed.'';
      type = types.str;
    };
    reqAlt = mkOption {
      default = false;
      description = ''Require alt to be held.'';
      type = types.bool;
    };
    reqCtrl = mkOption {
      default = true;
      description = ''Require control to be held.'';
      type = types.bool;
    };
    reqShift = mkOption {
      default = true;
      description = ''Require shift to be held.'';
      type = types.bool;
    };
  };
  toneIndicators = {
    enable = mkEnableOption ''Show tooltips for tone indicators like /srs, /gen, etc. in sent messages. (Equicord-only)'';
    customIndicators = mkOption {
      default = "";
      description = ''Custom tone indicators (format: jk=Joking; srs=Serious)'';
      type = types.str;
    };
    maxIndicators = mkOption {
      default = 5;
      description = ''Maximum number of tone indicators to show per message'';
      type = types.int;
    };
    prefix = mkOption {
      default = "/";
      description = ''Prefix character(s) for tone indicators.'';
      type = types.str;
    };
  };
  tosuRpc = {
    enable = mkEnableOption ''osu! RPC with data from tosu (Equicord-only)'';
  };
  translate = {
    enable = mkEnableOption ''Vencord's translate plugin but with support for artistic languages! (Equicord-only)'';
    shavian = mkOption {
      default = true;
      description = ''Enable Shavian (restart required)'';
      type = types.bool;
    };
    sitelen = mkOption {
      default = true;
      description = ''Enable Sitelen Pona (restart required)'';
      type = types.bool;
    };
    target = mkOption {
      default = "en";
      description = ''Target language (restart required)'';
      type = types.str;
    };
    toki = mkOption {
      default = true;
      description = ''Enable Toki Pona (restart required)'';
      type = types.bool;
    };
  };
  unitConverter = {
    enable = mkEnableOption ''Converts metric units to Imperal units and vice versa (Equicord-only)'';
    myUnits = mkOption {
      default = "imperial";
      description = ''the units you use and want things converted to. defaults to imperial'';
      type = types.enum [
        "imperial"
        "metric"
      ];
    };
  };
  universalMention = {
    enable = mkEnableOption ''Mention any user, regardless of channel access. (Equicord-only)'';
    globalMention = mkOption {
      default = false;
      description = ''Mention users from any server, not just the current one (restart required)'';
      type = types.bool;
    };
    onlyDmUsers = mkOption {
      default = false;
      description = ''Only show users you've had DMs with (restart required)'';
      type = types.bool;
    };
  };
  unlimitedAccounts = {
    enable = mkEnableOption ''Increases the amount of accounts you can add. (Equicord-only)'';
    maxAccounts = mkOption {
      default = 0;
      description = ''Number of accounts that can be added, or 0 for no limit (restart required)'';
      type = types.int;
    };
  };
  unreadCountBadge = {
    enable = mkEnableOption ''Shows unread message count badges on channels in the channel list (Equicord-only)'';
    notificationCountLimit = mkOption {
      default = false;
      description = ''Show +99 instead of true amount'';
      type = types.bool;
    };
    showOnMutedChannels = mkOption {
      default = false;
      description = ''Show unread count on muted channels'';
      type = types.bool;
    };
  };
  userPfp = {
    enable = mkEnableOption ''Allows you to use an animated avatar without Nitro (Equicord-only)'';
    databaseSource = mkOption {
      default = "https://userpfp.github.io/UserPFP/source/data.json";
      description = ''URL to load database from'';
      type = types.str;
    };
    preferNitro = mkOption {
      default = true;
      description = ''Which avatar to use if both default animated (Nitro) pfp and UserPFP avatars are present'';
      type = types.bool;
    };
  };
  vcNarratorCustom = {
    enable = mkEnableOption ''Announces when users join, leave, or move voice channels via narrator. TikTok TTS version; speechSynthesis is pretty boring. Ported from https://github.com/Loukious/Vencord (Equicord-only)'';
    customVoice = mkOption {
      default = "en_us_001";
      description = ''Custom voice id, currently just tiktok'';
      type = types.str;
    };
    deafenMessage = mkOption {
      default = "{{DISPLAY_NAME}} deafened";
      description = ''Deafen Message (only self for now)'';
      type = types.str;
    };
    ignoreSelf = mkOption {
      default = false;
      description = ''Ignore yourself for all events.'';
      type = types.bool;
    };
    joinMessage = mkOption {
      default = "{{DISPLAY_NAME}} joined";
      description = ''Join Message'';
      type = types.str;
    };
    latinOnly = mkOption {
      default = false;
      description = ''Strip non latin characters from names before saying them'';
      type = types.bool;
    };
    leaveMessage = mkOption {
      default = "{{DISPLAY_NAME}} left";
      description = ''Leave Message'';
      type = types.str;
    };
    moveMessage = mkOption {
      default = "{{DISPLAY_NAME}} moved to {{CHANNEL}}";
      description = ''Move Message'';
      type = types.str;
    };
    muteMessage = mkOption {
      default = "{{DISPLAY_NAME}} muted";
      description = ''Mute Message (only self for now)'';
      type = types.str;
    };
    rate = mkOption {
      default = 1.0;
      description = ''Narrator Speed'';
      type = types.float;
    };
    sayOwnName = mkOption {
      default = false;
      description = ''Say own name'';
      type = types.bool;
    };
    undeafenMessage = mkOption {
      default = "{{DISPLAY_NAME}} undeafened";
      description = ''Undeafen Message (only self for now)'';
      type = types.str;
    };
    unmuteMessage = mkOption {
      default = "{{DISPLAY_NAME}} unmuted";
      description = ''Unmute Message (only self for now)'';
      type = types.str;
    };
    volume = mkOption {
      default = 1.0;
      description = ''Narrator Volume'';
      type = types.float;
    };
  };
  vcPanelSettings = {
    enable = mkEnableOption ''Control voice settings right from the voice panel (Equicord-only)'';
    camera = mkOption {
      default = false;
      description = ''Show a camera selector'';
      type = types.bool;
    };
    inputDevice = mkOption {
      default = true;
      description = ''Show an input device selector'';
      type = types.bool;
    };
    inputVolume = mkOption {
      default = true;
      description = ''Show an input volume slider'';
      type = types.bool;
    };
    outputDevice = mkOption {
      default = true;
      description = ''Show an output device selector'';
      type = types.bool;
    };
    outputVolume = mkOption {
      default = true;
      description = ''Show an output volume slider'';
      type = types.bool;
    };
    showInputDeviceHeader = mkOption {
      default = false;
      description = ''Show header above input device selector'';
      type = types.bool;
    };
    showInputVolumeHeader = mkOption {
      default = true;
      description = ''Show header above input volume slider'';
      type = types.bool;
    };
    showOutputDeviceHeader = mkOption {
      default = false;
      description = ''Show header above output device selector'';
      type = types.bool;
    };
    showOutputVolumeHeader = mkOption {
      default = true;
      description = ''Show header above output volume slider'';
      type = types.bool;
    };
    showVideoDeviceHeader = mkOption {
      default = false;
      description = ''Show header above camera selector'';
      type = types.bool;
    };
    title1 = mkOption {
      default = { };
      type = types.attrs;
    };
    title2 = mkOption {
      default = { };
      type = types.attrs;
    };
    title3 = mkOption {
      default = { };
      type = types.attrs;
    };
    uncollapseSettingsByDefault = mkOption {
      default = false;
      description = ''Automatically uncollapse voice settings by default'';
      type = types.bool;
    };
  };
  vcSupport = {
    enable = mkEnableOption ''Wumpus Dance + Support Warnings (Equicord-only)'';
  };
  viewRawVariant = {
    enable = mkEnableOption ''Copy/View raw content of any message, channel, or guild, but show in the right click menu. (Equicord-only)'';
  };
  voiceButtons = {
    enable = mkEnableOption ''Quickly DM, mute, or deafen any user right from the voice-call panel. (Equicord-only)'';
    disableVideo = mkOption {
      default = true;
      description = ''Toggles their video upon clicking deafen button.'';
      type = types.bool;
    };
    muteSoundboard = mkOption {
      default = true;
      description = ''Toggles their soundboard upon clicking deafen button.'';
      type = types.bool;
    };
    serverSelf = mkOption {
      default = false;
      description = ''Deafen / Mute yourself on the server when using mute/deafen.'';
      type = types.bool;
    };
    showButtonsSelf = mkOption {
      default = "display";
      description = ''Whether you want to display buttons for your own user. Same functionality as other button(s) except it'll open DMs panel and mute/deafen for yourself upon clicking button(s). (restart required)'';
      type = types.enum [
        "display"
        "hide"
        "disable"
      ];
    };
    showChatButton = mkOption {
      default = true;
      description = ''Whether you want to display the chat button (restart required)'';
      type = types.bool;
    };
    showDeafenButton = mkOption {
      default = true;
      description = ''Whether you want to display the deafen button (restart required)'';
      type = types.bool;
    };
    showMuteButton = mkOption {
      default = true;
      description = ''Whether you want to display the mute button (restart required)'';
      type = types.bool;
    };
    useServer = mkOption {
      default = false;
      description = ''Use server mute/deafen instead of local when you have permission.'';
      type = types.bool;
    };
    whichNameToShow = mkOption {
      default = "both";
      description = ''Choose whether to show nickname or username in tooltip.'';
      type = types.enum [
        "global"
        "username"
        "both"
      ];
    };
  };
  voiceChannelLog = {
    enable = mkEnableOption ''Logs who joins and leaves voice channels (Equicord-only)'';
    ignoreBlockedUsers = mkOption {
      default = false;
      description = ''Do not log blocked users'';
      type = types.bool;
    };
    mode = mkOption {
      default = 1;
      description = ''
        How to show the voice channel log

        Values: 1 = Log menu, 2 = Log to associated chat directly, 3 = Log to chat and log menu'';
      type = types.enum [
        1
        2
        3
      ];
    };
    voiceChannelChatSelf = mkOption {
      default = true;
      description = ''Log your own voice channel events in the voice channels'';
      type = types.bool;
    };
    voiceChannelChatSilent = mkOption {
      default = true;
      description = ''Join/leave/move messages in voice channel chats will be silent'';
      type = types.bool;
    };
    voiceChannelChatSilentSelf = mkOption {
      default = false;
      description = ''Join/leave/move messages in voice channel chats will be silent if you are in the voice channel'';
      type = types.bool;
    };
  };
  voiceChatUtilities = {
    enable = mkEnableOption ''This plugin allows you to perform multiple actions on an entire channel (move, mute, disconnect, etc.) (originally by dutake) (Equicord-only)'';
    waitAfter = mkOption {
      default = 5.0;
      description = ''Amount of API actions to perform before waiting (to avoid rate limits)'';
      type = types.float;
    };
    waitSeconds = mkOption {
      default = 2.0;
      description = ''Time to wait between each action (in seconds)'';
      type = types.float;
    };
  };
  voiceJoinMessages = {
    enable = mkEnableOption ''Recieve client-side ephemeral messages when your friends join voice channels (Equicord-only)'';
    allowedFriends = mkOption {
      default = "";
      description = ''Comma or space separated list of friends' user IDs you want to recieve join messages from'';
      type = types.str;
    };
    friendDirectMessages = mkOption {
      default = true;
      description = ''Recieve notifications in your friends' DMs when they join a voice channel'';
      type = types.bool;
    };
    friendDirectMessagesSelf = mkOption {
      default = false;
      description = ''Recieve notifications in your friends' DMs even if you are in the same voice channel as them'';
      type = types.bool;
    };
    friendDirectMessagesShowMemberCount = mkOption {
      default = false;
      description = ''Show the count of other members in the voice channel when recieving a DM notification of your friend joining a voice channel'';
      type = types.bool;
    };
    friendDirectMessagesShowMembers = mkOption {
      default = true;
      description = ''Show a list of other members in the voice channel when recieving a DM notification of your friend joining a voice channel'';
      type = types.bool;
    };
    friendDirectMessagesSilent = mkOption {
      default = false;
      description = ''Join messages in your friends DMs will be silent'';
      type = types.bool;
    };
    ignoreBlockedUsers = mkOption {
      default = true;
      description = ''Do not send messages about blocked users joining/leaving/moving voice channels'';
      type = types.bool;
    };
  };
  voiceRejoin = {
    enable = mkEnableOption ''Rejoins DM/Server call automatically when restarting Discord. (Equicord-only)'';
    preventReconnectIfCallEnded = mkOption {
      default = "both";
      description = ''Do not reconnect if the call has ended or the voice channel is empty or does not exist.'';
      type = types.enum [
        "none"
        "dms"
        "servers"
        "both"
      ];
    };
    rejoinDelay = mkOption {
      default = 2.0;
      description = ''Set Delay before rejoining voice channel.'';
      type = types.float;
    };
  };
  wallpaperFree = {
    enable = mkEnableOption ''Recreation of the old DM wallpaper experiment; Set a background image for any channel, user or server. (Equicord-only)'';
    globalDefault = mkOption {
      default = { };
      description = ''Set a global default wallpaper for all channels.'';
      type = types.attrs;
    };
    stylingTips = mkOption {
      default = { };
      type = types.attrs;
    };
  };
  webpackTarball = {
    enable = mkEnableOption ''Converts Discord's webpack sources into a tarball. (Equicord-only)'';
    patched = mkOption {
      default = true;
      description = ''Include patched modules (restart required)'';
      type = types.bool;
    };
  };
  whitelistedEmojis = {
    enable = mkEnableOption ''Adds the ability to disable all message emojis except for a whitelisted set. (Equicord-only)'';
    defaultEmojis = mkOption {
      default = true;
      description = ''Hide default emojis'';
      type = types.bool;
    };
    disableToasts = mkOption {
      default = false;
      description = ''Disable toasts'';
      type = types.bool;
    };
    exportEmojis = mkOption {
      default = { };
      description = ''Export Emojis'';
      type = types.attrs;
    };
    importEmojis = mkOption {
      default = { };
      description = ''Import Emojis'';
      type = types.attrs;
    };
    resetEmojis = mkOption {
      default = { };
      description = ''Reset Emojis'';
      type = types.attrs;
    };
    serverEmojis = mkOption {
      default = true;
      description = ''Hide server emojis'';
      type = types.bool;
    };
    whiteListedEmojis = mkOption {
      default = { };
      description = ''Whitelisted Emojis'';
      type = types.attrs;
    };
  };
  whosWatching = {
    enable = mkEnableOption ''Hover over the screenshare icon to view what users are watching your stream (Equicord-only)'';
    showPanel = mkOption {
      default = true;
      description = ''Show spectators under screenshare panel (restart required)'';
      type = types.bool;
    };
  };
  wigglyText = {
    enable = mkEnableOption ''Adds a new markdown formatting that makes text wiggly. (Equicord-only)'';
    intensity = mkOption {
      default = 4.0;
      description = ''Animation intensity in px'';
      type = types.float;
    };
  };
  writeUpperCase = {
    enable = mkEnableOption ''Changes the first Letter of each Sentence in Message Inputs to Uppercase (Equicord-only)'';
    blockedWords = mkOption {
      default = "http, https, ok";
      description = ''Strings not to capitilise (seperate with a comma)'';
      type = types.str;
    };
  };
  youtubeDescription = {
    enable = mkEnableOption ''Adds descriptions to youtube video embeds (Equicord-only)'';
  };
}
