# This file is auto-generated by scripts/generate-plugin-options
# DO NOT EDIT this file directly; instead update the generator

{
  lowerPluginTitles = [
    "arRPCBun"
    "petpet"
  ];
  upperNames = [
    "webhook"
    "owner"
    "administrator"
    "moderatorStaff"
    "moderator"
    "voiceModerator"
    "chatModerator"
    "skipHostUpdate"
    "dangerousEnableDevtoolsOnlyEnableIfYouKnowWhatYoureDoing"
    "minWidth"
    "minHeight"
    "isMaximized"
    "isMinimized"
    "windowBounds"
    "openOnStartup"
    "minimizeToTray"
  ];
}
