# This file is auto-generated by scripts/generate-plugin-options
# DO NOT EDIT this file directly; instead update the generator

{
  fakeEnums = {
    four = [
      "competing"
    ];
    one = [
      "consistent"
      "always"
      "streaming"
      "discordUptime"
      "titles"
      "only@Mentions"
      "list"
      "datePosted"
      "better"
      "lowestRole"
      "custom"
      "preferDiscord"
      "enabled"
      "onlyServerCount"
      "cozy"
      "muted"
      "animatedDots"
      "blacklist"
    ];
    three = [
      "watching"
      "customTime"
      "serverDefault"
      "both"
    ];
    two = [
      "timestamp"
      "moreThanOne"
      "listening"
      "currentTime"
      "thumbnails"
      "nothing"
      "gallery"
      "projectX"
      "followNoReplyMention"
      "onlyFriendCount"
      "roomy"
      "avatars"
    ];
    zero = [
      "randomCharacters"
      "never"
      "playing"
      "none"
      "everything"
      "all"
      "recentlyActive"
      "normal"
      "highestRole"
      "mostRecent"
      "disabled"
      "compact"
      "plain"
      "whitelist"
    ];
  };
  lowerPluginTitles = [
    "arRPCBun"
    "petpet"
  ];
  upperNames = [
    "webhook"
    "owner"
    "administrator"
    "moderatorStaff"
    "moderator"
    "voiceModerator"
    "chatModerator"
    "skipHostUpdate"
    "dangerousEnableDevtoolsOnlyEnableIfYouKnowWhatYoureDoing"
    "minWidth"
    "minHeight"
    "isMaximized"
    "isMinimized"
    "windowBounds"
    "openOnStartup"
    "minimizeToTray"
  ];
}
