# This file is auto-generated by scripts/generate-plugin-options
# DO NOT EDIT this file directly; instead update the generator

{ lib, ... }:
let
  inherit (lib) types mkEnableOption mkOption;
in
{
  spotifyControls = {
    enable = mkEnableOption ''Adds a Spotify player above the account panel (Vencord-only)'';
  };
  vencordToolbox = {
    enable = mkEnableOption ''Adds a button to the titlebar that houses Vencord quick actions (Vencord-only)'';
    showPluginMenu = mkOption {
      default = true;
      description = ''Show the plugins menu in the toolbox'';
      type = types.bool;
    };
  };
}
