# This file is auto-generated by scripts/generate-plugin-options
# DO NOT EDIT this file directly; instead update the generator

{ lib, ... }:
let
  inherit (lib) types mkEnableOption mkOption;
in
{
  iLoveSpam = {
    enable = mkEnableOption ''Do not hide messages from 'likely spammers' (Vencord-only)'';
  };
  oneko = {
    enable = mkEnableOption ''cat follow mouse (real) (Vencord-only)'';
  };
  sortFriendRequests = {
    enable = mkEnableOption ''Sorts friend requests by date of receipt (Vencord-only)'';
    showDates = mkOption {
      default = false;
      description = ''Show dates on friend requests (restart required)'';
      type = types.bool;
    };
  };
  spotifyControls = {
    enable = mkEnableOption ''Adds a Spotify player above the account panel (Vencord-only)'';
  };
  streamerModeOnStream = {
    enable = mkEnableOption ''Automatically enables streamer mode when you start streaming in Discord (Vencord-only)'';
  };
  vencordToolbox = {
    enable = mkEnableOption ''Adds a button to the titlebar that houses Vencord quick actions (Vencord-only)'';
  };
  webRichPresence = {
    enable = mkEnableOption ''Client plugin for arRPC to enable RPC on Discord Web (experimental) (Vencord-only)'';
  };
}
