# This file is auto-generated by scripts/generate-plugin-options
# DO NOT EDIT this file directly; instead update the generator

{ lib, ... }:
let
  inherit (lib) types mkEnableOption mkOption;
in
{
  invisibleChat = {
    enable = mkEnableOption ''Encrypt your Messages in a non-suspicious way! (Vencord-only)'';
    savedPasswords = mkOption {
      default = "password, Password";
      description = ''Saved Passwords (Seperated with a , )'';
      type = types.str;
    };
  };
  spotifyControls = {
    enable = mkEnableOption ''Adds a Spotify player above the account panel (Vencord-only)'';
  };
  vencordToolbox = {
    enable = mkEnableOption ''Adds a button to the titlebar that houses Vencord quick actions (Vencord-only)'';
  };
}
